// const public_key = "GBFNM2W3QNSPR4KGY4FNEF6YUF7STM5LF5VOARFCCQCSLPZMSEQTZ4MU"
// const private_key = "SCF5KGC7HMU2YN5ZTY5SPTIRSDPWHYZDIPQTQZM2NF4AGNPWEJKKGFGY"

const public_key = "GCXEQNLGRDKEPUPLCZRGXYKAUQSI4Y56OHJPM4N35ZYZGH4LXMVUK5SD"
const private_key = "SBPFHJYPXKTN57UFHXM72UGOFREECEM2TAKFVSZDFBTKMQ5VFDYKWH5W"

module.exports.public_key = public_key
module.exports.private_key = private_key