const public_key = "GB2DOWKNWFB67473X5EBUEEIVSEWQ3PFMHMXEWIUAP3J2XYTBDGTTLTS"
const private_key = "SAKOT6TVCQEHORLKQNZB5MICL3USVF2TGU5ZHZFM627VUCVU5BBVX2K5"

// const public_key = "GCXEQNLGRDKEPUPLCZRGXYKAUQSI4Y56OHJPM4N35ZYZGH4LXMVUK5SD"
// const private_key = "SBPFHJYPXKTN57UFHXM72UGOFREECEM2TAKFVSZDFBTKMQ5VFDYKWH5W"

module.exports.public_key = public_key
module.exports.private_key = private_key